package Lexer;

public enum TokenType {
    RESOURCE, TAG, CONDITIONS, IF, PARENT, CHILD, HAS, CLASS, ATTRIBUTE,
    OR, AND, EXPORT, TO, SET, FIELDS, TEXT, IMG, EVERY, FROM, THIS, AMOUNT,
    NO, FIELD,
    LEFT_BOX_BRACKET, RIGHT_BOX_BRACKET,
    LEFT_BRACE, RIGHT_BRACE,
    EQUAL, NOT_EQUAL, ASSIGN_OPERATOR,
    DOT, SEMI_COLON,
    NUMBER, STRING
}
